### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.data_augmentation'

### ISSUE THREAD

**Issue by JingyiXu404** [haesoochung/hdri-saturation-compensation#3]
raise error at:
from utils.data_augmentation import *

**Comment by haesoochung** [comment]
in which file?

**Comment by yizhitangsen** [comment]
This error occurs on line 14 of the "utils.py" file

**Comment by haesoochung** [comment]
Actually, you don't need that file. I modified utils.py.
Sorry for the confusion.
